name: Bug
description: You discover a bug
title: "[BUG] <title>"
body:
  - type: textarea
    attributes:
      label: What Happened
      description: |
        Tell us what happened with the bug you encounter.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behaviour
      description: |
        Tell us what you wanted to happen instead
    validations:
      required: true
  - type: textarea
    attributes:
      label: How To Reproduce
      description: |
        Tell us the different states to reproduce this bug, please tell us everything about your environment (OS, npm version...)
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Any Idea ?
      description: |
        Maybe you have an idea on how to fix this bug ? Tell us everything !
    validations:
      required: false
