name: Feature request
description: This is a totally new project so obviously it need a lot of new feature. So please tell us what you think this project need !
body:
  - type: textarea
    attributes:
      label: Description
      description: Tell us about this feature!
    validations:
      required: true
  - type: textarea
    attributes:
      label: How ? 
      description: Do you already have an idea of how to implement it ?
    validations:
      required: false
  - type: dropdown
    attributes:
      label: How important is this feature ?
      multiple: false
      options:
        - Not Important
        - Important
        - Really Important
